

;------------------------------------------------------------------[ Sprite layouts per level
tiger_level0_sprites
	.byte	$00, $22, $00
	.byte	$00, $25, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level1_sprites
	.byte	$21, $22, $24
	.byte	$00, $25, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level2_sprites
	.byte	$00, $22, $00
	.byte	$00, $23, $00
	.byte	$00, $25, $00
	.byte	$00, $00, $00

tiger_level3_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$00, $25, $00
	.byte	$00, $00, $00

tiger_level4_sprites
	.byte	$00, $22, $00
	.byte	$00, $23, $00
	.byte	$00, $23, $00
	.byte	$00, $25, $00

tiger_level5_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$21, $23, $24
	.byte	$00, $25, $00

tiger_level6_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$21, $23, $24
	.byte	$00, $25, $00

tiger_level7_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$21, $23, $24
	.byte	$00, $25, $00

tiger_level8_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$21, $23, $24
	.byte	$00, $25, $00

tiger_level9_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$21, $23, $24
	.byte	$00, $25, $00

tiger_levelA_sprites
	.byte	$00, $22, $00
	.byte	$21, $23, $24
	.byte	$21, $23, $24
	.byte	$00, $25, $00

;------------------------------------------------------------------[ Health figures per level
tiger_level0_health
	.byte	$00, $18, $00
	.byte	$00, $10, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level1_health
	.byte	$10, $1C, $10
	.byte	$00, $10, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level2_health
	.byte	$00, $20, $00
	.byte	$00, $18, $00
	.byte	$00, $10, $00
	.byte	$00, $00, $00

tiger_level3_health
	.byte	$00, $20, $00
	.byte	$10, $18, $10
	.byte	$00, $10, $00
	.byte	$00, $00, $00

tiger_level4_health
	.byte	$00, $28, $00
	.byte	$00, $1C, $00
	.byte	$00, $1C, $00
	.byte	$00, $10, $00

tiger_level5_health
	.byte	$00, $30, $00
	.byte	$18, $20, $18
	.byte	$18, $20, $18
	.byte	$00, $18, $00

tiger_level6_health
	.byte	$00, $38, $00
	.byte	$20, $28, $20
	.byte	$20, $28, $20
	.byte	$00, $20, $00

tiger_level7_health
	.byte	$00, $40, $00
	.byte	$28, $30, $28
	.byte	$28, $30, $28
	.byte	$00, $28, $00

tiger_level8_health
	.byte	$00, $48, $00
	.byte	$30, $38, $30
	.byte	$30, $38, $30
	.byte	$00, $30, $00

tiger_level9_health
	.byte	$00, $50, $00
	.byte	$38, $40, $38
	.byte	$38, $40, $38
	.byte	$00, $38, $00

tiger_levelA_health
	.byte	$00, $60, $00
	.byte	$40, $50, $40
	.byte	$40, $50, $40
	.byte	$00, $40, $00


;------------------------------------------------------------------[ Shot patterns
tiger_level0_patterns
	.byte	$00, $01, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level1_patterns
	.byte	$01, $01, $01
	.byte	$00, $00, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level2_patterns
	.byte	$00, $01, $00
	.byte	$00, $02, $00
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level3_patterns
	.byte	$00, $01, $00
	.byte	$01, $01, $01
	.byte	$00, $00, $00
	.byte	$00, $00, $00

tiger_level4_patterns
	.byte	$00, $01, $00
	.byte	$00, $01, $00
	.byte	$00, $01, $00
	.byte	$00, $00, $00

tiger_level5_patterns
	.byte	$00, $01, $00
	.byte	$01, $01, $01
	.byte	$01, $01, $01
	.byte	$00, $00, $00

tiger_level6_patterns
	.byte	$00, $01, $00
	.byte	$01, $01, $01
	.byte	$01, $01, $01
	.byte	$00, $00, $00

tiger_level7_patterns
	.byte	$00, $01, $00
	.byte	$01, $01, $01
	.byte	$01, $01, $01
	.byte	$00, $00, $00

tiger_level8_patterns
	.byte	$00, $01, $00
	.byte	$01, $01, $01
	.byte	$01, $01, $01
	.byte	$00, $00, $00

tiger_level9_patterns
	.byte	$00, $01, $00
	.byte	$01, $01, $01
	.byte	$01, $01, $01
	.byte	$00, $00, $00

tiger_levelA_patterns
	.byte	$00, $01, $00
	.byte	$03, $02, $03
	.byte	$00, $00, $00
	.byte	$00, $00, $00

;------------------------------------------------------------------[ Row/Col Matrix
tiger_block_rows
	.byte	$00, $00, $00
	.byte	$01, $01, $01
	.byte	$02, $02, $02
	.byte	$03, $03, $03

tiger_block_columns
	.byte	$E0, $F8, $10
	.byte	$E0, $F8, $10
	.byte	$E0, $F8, $10
	.byte	$E0, $F8, $10
;	.byte	$E8, $00, $18
;	.byte	$E8, $00, $18
;	.byte	$E8, $00, $18
;	.byte	$E8, $00, $18

;------------------------------------------------------------------[ TigerMoth pathing per level
tiger_level0_path_x		.byte	$98, $80, $60, $73, $A0, $B4, $D8, $C0
tiger_level0_path_y		.byte	$40, $66, $2E, $34, $80, $3C, $62, $40

